[phases.setup]
cmds = [
  "cd server && npm ci --only=production",
  "cd client && npm ci --only=production"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[phases.install]
cmds = [
  "mkdir -p database"
]

[start]
cmd = "cd server && node index.js"
